version: '3'

services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - server
      
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

